version: '3.7'

services:
  postgres:
    image: postgres:13.3-alpine
    restart: "no"
    volumes:
      - pg-datavolume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: db-user
      POSTGRES_PASSWORD: db-pass
      POSTGRES_DB: db-name
    ports:
      - "5432:5432"
volumes:
  pg-datavolume:
