RELEASE_PKG := main
BUILD_VERSION ?= $(shell git rev-parse --short=8 HEAD || echo unknown)
LDFLAGS := -X '$(RELEASE_PKG).Version=local-baby'
LDFLAGS += -X '$(RELEASE_PKG).DBUser=db-user'
LDFLAGS += -X '$(RELEASE_PKG).DBPass=db-pass'
LDFLAGS += -X '$(RELEASE_PKG).DBHost=localhost:5432'
LDFLAGS += -X '$(RELEASE_PKG).DBName=db-name'

build:
	go build -v -ldflags "-s $(LDFLAGS)"
